# Rename this file to languages.toml to enable multilingual support

[en]
languageName = "English"
label = "English"
languageDirection = "ltr"
title = "Kyle's Blog"
weight = 1

[zh]
languageName = "中文"
label = "中文"
languageDirection = "ltr"
title = "陈默的博客"
weight = 2

