# Rename this file to languages.toml to enable multilingual support

[zh-cn]
languageName = "中文"
languagedirection = "zh-cn"
title = "陈默的博客"
weight = 1

[en]
languageName = "English"
languagedirection = "en"
title = "Example Site"
weight = 2

