# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["posts"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.ico"

SortBy = "default"

[footer]
since = 2023
customText = ""

[dateFormat]
published = "2006-01-02"
lastUpdated = "2006-01-02"

[sidebar]
emoji = ""
subtitle = "Nothing happened to me"
avatar = "img/avatar.jpg"

[article]
headingAnchor = false
math = true
readingTime = true

[article.license]
enabled = false
default = "Licensed under CC BY-NC-SA 4.0"

[article.alertIcon]
note      = "📝"
tip       = "💡"
important = "📌"
warning   = "⚠️"
caution   = "🚨"

[article.mermaid]
look                  = "classic"
lightTheme            = "default"
darkTheme             = "dark"
securityLevel         = "strict"
htmlLabels            = true
transparentBackground = false

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"


[colorScheme]
toggle = true
default = "auto"

[imageProcessing.thumbnail]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "utterances"

[comments.utterances]
repo = "chenkeao/blog_comments"
issueTerm = "pathname"
label = ""
